Linking and auto linking on oauth2 registration
mgjm/gitea pull request #1
Opened 2021-03-27 16:02 UTC by kvaster

Added option GOOGLE_CONNECT_SCOPES - scopes for google provider (we're using this one). There is no profile information without profile scope.
Added option USE_EMAIL - to use username part of email for 'name'. This is extremly usefull for google provider.
Added option SHOW_ACCOUNT_LINKING_LOGIN - if enabled account linking login page will be displayed in case already exist.
Added option ENABLE_AUTO_REGISTRATION_LINKING - if enabled account will be linked automatically in case already exist.
Added option UPDATE_AVATAR - avatar will be automatically updated on login if enabled and avatar_url is available from ouath2 provider
Added migration for avatar_url in external_login_user. Currently it is restricted to 255 chars, but google sends us urls 850 chars len.
Some side effects: If you have (for example) two auths - ldap and google. If user will register with ldap and later will try to login with google - it will work. But if user will register with google he will be not able to login/link with ldap credentials. This is cause of user accounts design in gitea.

Also this patch does not respect 'remember' option in case of auto linking.

2021-03-29 14:19 UTC, mgjm commented
Thanks for the PR. These are some very useful features. 👍 

I will add a few suggestions as I read through the code.

2021-03-29 15:03 UTC, mgjm requested changes
Would you like to have a go at implementing the changes, or should I do it?

2021-03-29 15:03 UTC, mgjm commented on custom/conf/app.example.ini
> +GOOGLE_CONNECT_SCOPES =
This should just be `GOOGLE_SCOPES`

2021-03-29 15:03 UTC, mgjm commented on custom/conf/app.example.ini
> +USE_EMAIL = false
One combined setting for `USE_NICKNAME` and `USE_EMAIL`:
```ini
; The source of the username for new oauth2 accounts:
; userid = use the userid / sub attribute
; nickname = use the nickname attribute
; email = use the username part of the email attribute
USERNAME = userid
```

2021-03-29 15:03 UTC, mgjm commented on custom/conf/app.example.ini
> +ENABLE_AUTO_REGISTRATION_LINKING = false
One combined setting for `SHOW_ACCOUNT_LINKING_LOGIN ` and `ENABLE_AUTO_REGISTRATION_LINKING `:
```ini
; How to handle if an account / email already exists:
; disabled = show an error
; login = show an account linking login
; automatic = link directly with the account
ACCOUNT_LINKING = disabled
```

2021-03-29 15:03 UTC, mgjm commented on routers/user/auth.go
> +				return false, true
We can move the block to handle an existing account ([line 650-667](https://github.com/mgjm/gitea/pull/1/files#diff-26916e6c099f420990c949e5741169245c448ee89eb2089db1773a0857e5faa3R650-R667)) into this function.

Then we do not need to return two booleans. (Only the `ok bool`)
It seems too easy for me to mix up the order in the future.

2021-03-29 15:03 UTC, mgjm commented on routers/user/auth.go
> +			if err == nil {
We should respect the `setting.Avatar.MaxFileSize`:
```suggestion
			data, err := io.ReadAll(io.LimitReader(resp.Body, setting.Avatar.MaxFileSize + 1))
			if err == nil && len(data) <= setting.Avatar.MaxFileSize {
```

2021-03-29 15:03 UTC, mgjm commented on routers/user/auth.go
> +		resp, err := http.Get(url)
We need to close the `resp.Body` (according to [go docs](https://golang.org/pkg/net/http/#Client.Get)):
```go
if err == nil {
  defer resp.Body.Close()
}
```

2021-03-29 17:55 UTC, kvaster commented
I will do changes tomorrow morning. Thanks for the review.

2021-03-30 08:31 UTC, kvaster commented on custom/conf/app.example.ini
> +GOOGLE_CONNECT_SCOPES =
Fixed

2021-03-30 08:33 UTC, kvaster commented on routers/user/auth.go
> +				return false, true
Fixed, but I had to pass gothUser to `createUserInContext`

2021-03-30 10:01 UTC, mgjm approved these changes
LGTM

2021-03-30 10:08 UTC, merged